services:
  esphome:
    image: esphome/esphome
    container_name: esphome
    restart: always
    ports:
      - "6052:6052" # ESPHome default web interface port
    volumes:
      - ./config:/config
    networks:
      - esphome_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "443:443"
    networks:
      - esphome_network

networks:
  esphome_network:
    driver: bridge
